{"name": "test06", "status": "passed", "description": "assert that you get a exception when you type invalid email adress", "start": 1710321466256, "stop": 1710321469153, "uuid": "30dd27c4-692f-4763-860d-39810953a227", "historyId": "b9b530c5cc25f8123ba9c34a7ef66853", "testCaseId": "b9b530c5cc25f8123ba9c34a7ef66853", "fullName": "test_cases.Test_cases#test_assert_exception_message_when_type_invalid_email", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_webdriver')"}, {"name": "suite", "value": "test_cases"}, {"name": "subSuite", "value": "Test_cases"}, {"name": "host", "value": "LAPTOP-C1F79DIL"}, {"name": "thread", "value": "10972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases"}]}